---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: status-rbac
  namespace: ava
subjects:
  - kind: ServiceAccount
    name: ava
    namespace: ava
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io