---
apiVersion: v1
kind: Service
metadata:
  name: k8s-status
  namespace: ava
  labels:
    app: k8s-status
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32090
      protocol: TCP
  selector:
    app: k8s-status